spring.application.name=HealthAppBackendJava
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/healthdb}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.secret=${"JWT_SECRET:ashu8797AshuJaat@@0087##7830!!0065"}

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:diksobgyg}
cloudinary.api-key=${CLOUDINARY_API_KEY:375638613787127}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:Bq4jvcwmPuP5oF9dukk8IPoOTwU}
cloudinary.enabled=${CLOUDINARY_ENABLED:false}

file-storage.local-directory=${FILE_STORAGE_LOCAL_DIRECTORY:uploads/profile-pictures}
app.base-url=${APP_BASE_URL:http://localhost:8080}
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

spring.data.redis.host=redis
spring.data.redis.port=6379
